### ISSUE TITLE
Naming consistency: neighbourhoods VS neighborhoods

### ISSUE THREAD

**Issue by emdann** [MikeDMorgan/miloR#10]
For some functions we have one, for some the other. 

Also it's quite long to write all the time. I would be pro using `nhoods` everywhere instead.

**Comment by MikeDMorgan** [comment]
Yeah, the strictly English spelling is neighbourhoods - but I keep mistyping.  I fully support going wholesale for nhoods - it's going to piss off users having to write this out the whole time. I'll put together a separate branch to fix this.

**Comment by emdann** [comment]
Mental sanity: restored :white_check_mark:

**Comment by MikeDMorgan** [comment]
Fixed and merged into master.
