### ISSUE TITLE
buildGraph recomputes the PCA when it's already there

### ISSUE THREAD

**Issue by emdann** [MikeDMorgan/miloR#13]
What is the purpose of this conditional statement supposed to be?  https://github.com/MikeDMorgan/miloR/blob/e86041a824c4308956ce59ce46aa7b383da9205a/R/buildGraph.R#L68

If I have a `Milo` object with only one slot named `PCA` in `reducedDim(x)` it wants to recompute the PCA.

**Comment by MikeDMorgan** [comment]
Good catch - 8a387cb should fix this - just running tests to be sure.

**Comment by MikeDMorgan** [comment]
Tests passed.
