### ISSUE TITLE
Problems with logcounts for calcNhoodsExpression

### ISSUE THREAD

**Issue by emdann** [MikeDMorgan/miloR#18]
The function complains about `logcounts(x)`:
```r
> x <- calcNhoodExpression(x, assay = "logcounts", subset.row = hvgs)
Error in t.default(data.set[subset.row, ]) : argument is not a matrix
```
Not sure what's wrong, just running `t(logcounts(x))[subset_rows,]` works fine.

If I try to convert `logcounts(x)` to a non-sparse matrix the function never ends, the R session crashes, all burns 🔥

**Comment by MikeDMorgan** [comment]
Could you give me a reproducible example with data? What is the class of `x` and how big is it?

**Comment by emdann** [comment]
```r
> liver_milo
class: Milo 
dim: 23498 58358 
metadata(0):
assays(2): counts logcounts
rownames(23498): FO538757.2 AP006222.2 ... CTA-126B4.7 LINC01423
rowData names(0):
colnames(58358): Healthy1_Cd45+_AAACCTGCAGTATCTG Healthy1_Cd45+_AACTGGTTCATGGTCA ... Cirrhotic3_Cd45-_TTTGTCATCCAGGGCT
  Cirrhotic3_Cd45-_TCTGGAAGTCATCCCT
colData names(10): nGene nUMI ... annotation_indepth annotation_lineage
reducedDimNames(2): PCA UMAP
spikeNames(0):
altExpNames(0):
nhoods dimensions(1): 4973
nhoodCounts dimensions(2): 4973 20
nhoodDistances dimensions(2): 58358 58358
graph names(1): graph
nhoodIndex names(1): 4973
nhoodExpression dimension(2): 3000 4973
nhoodReducedDim names(2): PCA UMAP
```
```
> calcNhoodExpression(liver_milo)
Error in t.default(data.set) : argument is not a matrix
```

Should I send you the milo object in RDS?

**Comment by emdann** [comment]
```
> class(logcounts(liver_milo))
[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"
```

**Comment by MikeDMorgan** [comment]
What is the class of `logcounts(x))[subset_rows,]`?

**Comment by emdann** [comment]
```r
> class(logcounts(liver_milo)[hvgs,])
[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"
> head(hvgs)
[1] "CCL4"    "HLA-DRA" "CCL3"    "NKG7"    "CCL5"    "KLRB1"  
```

**Comment by MikeDMorgan** [comment]
OK, send me the  RDS file and I'll investigate, I'm not sure exactly what is happening there.

**Comment by emdann** [comment]
On it's way

**Comment by MikeDMorgan** [comment]
I have a somewhat sneaky feeling that not all of the `Matrix` package functions are available inside the `.calc_expression` namespace, so it's not using the correct `t()` function, i.e. it's using the base::t() rather than Matrix::t(). I think, but it's basically impossible to tell as `Matrix` is imported by several other packages so can't be unloaded in an interactive session. add '@import Matrix' to `.calc_expression` seems to have fixed it, but it's slow running.

**Comment by MikeDMorgan** [comment]
I'm going to say that 85255a5 is a patch, as it doesn't preserve the rownames at the moment...
