### ISSUE TITLE
Need 4 speed

### ISSUE THREAD

**Issue by emdann** [MikeDMorgan/miloR#2]
The `buildGraph` function is significantly slower than `scran::buildKNNGraph`. Here on a simulated dataset of 2000 cells:
```
> system.time(sim_milo <- buildGraph(sim_milo, k = 20,d = 30))
Constructing kNN graph with k:20
Retrieving distances from 20 nearest neighbours
   user  system elapsed 
 12.897   0.767  13.702 
> system.time(sim2.knn <- buildKNNGraph(x=reducedDim(sim_milo, "PCA")[, c(1:30)], k=10, d=NA, transposed=TRUE))
   user  system elapsed 
  0.111   0.002   0.113 
```
On the human thymus dataset (~ 30k cells) it takes forever. Any idea on what's the bottleneck here?

**Comment by MikeDMorgan** [comment]
I wonder if this is related to the Milo object size. The only other difference between functions is the retrieval of distances - I'm a little surprised that slows things down so much.

**Comment by MikeDMorgan** [comment]
This was down to instantiating the distance matrix as sparse, but then filling it in the for loop which required multiple coercions to a non-sparse format from the `]<-` function in `Matrix`. Totally unexpected. Commit 9f59afe7202bbcb10de291b4547e8d5f90482a1e now makes things considerably faster:
```
> system.time(mylo <- buildGraph(mylo, k=21, d=30))
Constructing kNN graph with k:21
Retrieving distances from 21 nearest neighbours
   user  system elapsed 
  2.189   0.407   2.675 
> 
> system.time(mylo <- scran::buildKNNGraph(reducedDim(my.sce, "PCA"), k=21, d=NA, transposed=TRUE))
   user  system elapsed 
  0.871   0.024   0.916 
```
This is at least now in roughly the same ball park as the scran function - there _might_ be room for improvement, and we might need to keep an eye on the memory usage, but I think it should be a good fix for now.
