### ISSUE TITLE
findNhoodMarkers doesn't return the nhood groups

### ISSUE THREAD

**Issue by emdann** [MikeDMorgan/miloR#28]
This would be useful for plotting purposes

**Comment by MikeDMorgan** [comment]
It's on my to do list, sorry - it should be fairly trivial to do this.

**Comment by emdann** [comment]
I'd also add and option to subset nhoods for testing. E.g. in the liver case I want to do the test just in one lineage. I can subset manually the Milo obj and the results data.frame, but it would be a nice feature.

**Comment by MikeDMorgan** [comment]
65fbb33 should solve this. Could you add the subsetting feature as a separate issue?

**Comment by emdann** [comment]
Sorry for not clarifying earlier, what I meant here is returning an assignment of nhoods to groups, rather than cells to groups. This I could use to make a grouped heatmap of the `nhoodExpression(x)` matrix. Do you think this would be useful?

**Comment by emdann** [comment]
(or for subsetting the nhoodExpression matrix)

**Comment by MikeDMorgan** [comment]
I think this might be better off as a completely separate function that specifically returns the nhood groups in that case. It should be fairly trivial as the main worker functions are already in the `testDiffExp.R` file. This will require some refactoring, and probably worth moving the `.group_nhoods_by_overlap` to the `utility.R` file instead.

I'm working on the tests for both DGE functions at the moment - feel free to have a go at creating a specific subsetting function, but leave `.group_nhoods_by_overlap` in place for now.
