### ISSUE TITLE
Faster findNhoodMarkers

### ISSUE THREAD

**Issue by emdann** [MikeDMorgan/miloR#40]
`findNhoodMarkers` can be quite slow, and the critical step seems to be the `.group_nhoods_by_overlap` function. I noticed that also here there is some looping in between many pairs of nhoods, similar to what was slowing down `buildNhoodGraph` before  https://github.com/MikeDMorgan/miloR/pull/39/commits/42db3c4f9adf38475eb1234fbc3c8e0ddd99d601 :
https://github.com/MikeDMorgan/miloR/blob/4b192a3b90a2118055f2c4dfdeb80870f486c702/R/testDiffExp.R#L268

Maybe it could be refactored in a similar way? Or could the graph stored in the `nhoodGraph` slot be used here?

**Comment by MikeDMorgan** [comment]
I'm definitely not adverse to speeding this up - do you want to have a go?

**Comment by MikeDMorgan** [comment]
Fixed in #41
