### ISSUE TITLE
Package data format

### ISSUE THREAD

**Issue by emdann** [MikeDMorgan/miloR#44]
Having a look at the dataset included in the package, I wonder if we should load these as `SingleCellExperiment` objects to demonstrate usage the `Milo` constructor?

**Comment by MikeDMorgan** [comment]
Yeah, that's probably easier. It also means that if we change anything in the `Milo` class then we won't have a load of invalid data objects creating issues. I'll regenerate them as SCEs and upload.

**Comment by MikeDMorgan** [comment]
Remedied in 39cd9fe. I've removed the `Milo` object as the data were too big otherwise.
