### ISSUE TITLE
misleading message

### ISSUE THREAD

**Issue by emdann** [MikeDMorgan/miloR#47]
Minor: running `buildFromAdjacency` still throws a message `Adding nhoodDistances to Milo object`, but the `nhoodDistances` slot is not populated anymore.

**Comment by MikeDMorgan** [comment]
Cool - I'll take this out.

**Comment by MikeDMorgan** [comment]
Create new function for workflows that start with a distance matrix so that they can add the distance matrix _after_ defining neighbourhoods.

**Comment by MikeDMorgan** [comment]
Strictly this can be done by setting the `nhoodDistances` slot explicitly with a user-defined matrix. This should be done _after_ constructing the object and graph from `buildFromAdjacency`.
