### ISSUE TITLE
`data` param meaning different things in different functions

### ISSUE THREAD

**Issue by emdann** [MikeDMorgan/miloR#6]
A minor thing: both `countCells` and `testNeighbourhoods` have a required parameter called `data`, but for counting this needs to be the `colData` of the `Milo` object, while for testing it's the design matrix. I would change the name to `design_df` or something like that in `testNeighbourhoods`.

**Comment by MikeDMorgan** [comment]
Fixed in d30e84e. Each function now has a separate parameter; `design.df` for `testNeighbourhoods` and `meta.data` for `countCells`.
