### ISSUE TITLE
Something broken with .is_empty in testNeighbourhoods

### ISSUE THREAD

**Issue by emdann** [MikeDMorgan/miloR#9]
I get this error when running `testNeighbourhoods`:
```r
> milo_results <- testNeighbourhoods(sim_milo, ~ 1 + condition, design.df = design_df, fdr.weighting = "k-distance")
Error in rowSums(x.slot) : 
  'x' must be an array of at least two dimensions
```

I found [this comment](https://github.com/hemberg-lab/SC3/issues/53#issuecomment-355736905) suggesting that it might be an underlying problem of having a matrix of class `dgCMatrix` in `SingleCellExperiment` slots, but if I convert the counts to a regular matrix I get a weirder error:
```r
> neighbourhoodCounts(sim_milo) <- as.matrix(neighbourhoodCounts(sim_milo))
the condition has length > 1 and only the first element will be used
> milo_results <- testNeighbourhoods(sim_milo, ~ 1 + condition, design.df = design_df,
+                                fdr.weighting = "k-distance")
the condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedError in if (.is_empty(x, "neighbourhoodCounts")) { : 
  argument is of length zero
```

Any suggestions here

**Comment by emdann** [comment]
The problem here is with `.is_empty` not using the `rowSums` function from `Matrix` in , because if I put `Matrix::rowSums` in the function it works fine. Not sure how to fix this.

**Comment by MikeDMorgan** [comment]
I don't know why it's not using rowSums from Matrix - this should have been fixed in d30e84e95fc9957a7e871d214abbc2f386144b84:
`#' @importFrom Matrix rowSums`

**Comment by MikeDMorgan** [comment]
@emdann I haven't seen this issue arise since d30e84e - can you confirm, if it's fixed I'll close this issue.

**Comment by MikeDMorgan** [comment]
I've now refactored this into utils.R and rename .check_empty so it can be used in multiple functions.
